In [1]:
import tensorflow as tf

 **1. Create a vector, scalar, matrix and tensor with values of your choice using tf.constant()**

In [7]:
# Create a scalar
scalar = tf.constant(5)
print("Scalar:", scalar)

Scalar: tf.Tensor(5, shape=(), dtype=int32)


In [8]:
# Create a vector
vector = tf.constant([1, 2, 3])
print("Vector:", vector)

Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [9]:
# Create a matrix
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)

Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [10]:
# Create a tensor
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:", tensor)

Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


**2.Find the shape, rank and size of the tensors (which you created for Q1).**

In [14]:
print("Scalar - Shape:", scalar.shape, "Rank:", tf.rank(scalar).numpy(), "Size:", tf.size(scalar).numpy())
print("Vector - Shape:", vector.shape, "Rank:", tf.rank(vector).numpy(), "Size:", tf.size(vector).numpy())
print("Matrix - Shape:", matrix.shape, "Rank:", tf.rank(matrix).numpy(), "Size:", tf.size(matrix).numpy())
print("Tensor - Shape:", tensor.shape, "Rank:", tf.rank(tensor).numpy(), "Size:", tf.size(tensor).numpy())

Scalar - Shape: () Rank: 0 Size: 1
Vector - Shape: (3,) Rank: 1 Size: 3
Matrix - Shape: (2, 2) Rank: 2 Size: 4
Tensor - Shape: (2, 2, 2) Rank: 3 Size: 8


**3.Create two tensors containing random values between 0 and 1 with shape [5,300].**

In [15]:
# Create two tensors with random values between 0 and 1, with shape [5, 300]
tensor1 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)
tensor2 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)

print("Tensor 1:")
print(tensor1)
print("Tensor 2:")
print(tensor2)

Tensor 1:
tf.Tensor(
[[0.50866926 0.34323585 0.06875312 ... 0.70398474 0.28436804 0.954795  ]
 [0.4407617  0.24972486 0.75140464 ... 0.46400607 0.5011853  0.9745331 ]
 [0.41005445 0.5672165  0.4730302  ... 0.39044487 0.3019532  0.5403255 ]
 [0.74893045 0.39412177 0.46800804 ... 0.6631292  0.5188091  0.34921432]
 [0.52533185 0.32006168 0.5434861  ... 0.7179241  0.7723274  0.3415686 ]], shape=(5, 300), dtype=float32)
Tensor 2:
tf.Tensor(
[[0.8037964  0.9401088  0.16081488 ... 0.714708   0.74110925 0.42733443]
 [0.04235852 0.33751655 0.44583797 ... 0.68953884 0.97895205 0.6400398 ]
 [0.4674623  0.31654525 0.43272936 ... 0.9307698  0.43508494 0.6753799 ]
 [0.73404264 0.4311341  0.19812346 ... 0.8996655  0.72960484 0.05689728]
 [0.9880637  0.20429504 0.6000763  ... 0.13621819 0.01385868 0.28384137]], shape=(5, 300), dtype=float32)


**4.Multiply the two tensors (which you created for Question 3) using matrix multiplication. **

In [16]:
# Create two tensors with random values between 0 and 1, with shape [5, 300]
tensor1 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)
tensor2 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)


In [17]:
# Perform matrix multiplication
result = tf.matmul(tensor1, tensor2, transpose_b=True)

In [18]:
# Print the resulting tensor
print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
tf.Tensor(
[[69.910835 72.72605  78.3583   72.24144  73.18646 ]
 [69.678955 76.18139  79.70685  73.566666 74.53197 ]
 [71.33916  74.29613  78.62572  72.7796   77.28064 ]
 [67.68257  73.377625 78.45811  70.747765 71.62793 ]
 [68.02311  76.95296  76.86586  75.7589   77.96804 ]], shape=(5, 5), dtype=float32)


**5.Multiply the two tensors (which you created for Question 3) using dot product.**

In [20]:
# Create two tensors with random values between 0 and 1, with shape [5, 300]
tensor1 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)
tensor2 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)

In [22]:
# Compute the dot product
dot_product = tf.tensordot(tensor1, tensor2, axes=[[1], [1]])


In [23]:
# Print the resulting tensor
print("Result of dot product:")
print(dot_product)

Result of dot product:
tf.Tensor(
[[73.01307  75.611565 73.757515 69.46524  73.84509 ]
 [75.95446  78.40941  75.29412  69.9543   73.48273 ]
 [79.73375  84.68331  79.797615 79.57023  78.26837 ]
 [73.06737  75.45175  71.85271  71.42295  68.94172 ]
 [75.11339  80.94206  75.51499  76.22696  74.56004 ]], shape=(5, 5), dtype=float32)
