In [1]:
import tensorflow as tf

 **1. Create a vector, scalar, matrix and tensor with values of your choice using tf.constant()**

In [3]:
# Create a scalar
scalar = tf.constant(5)
print("Scalar:", scalar)

Scalar: tf.Tensor(5, shape=(), dtype=int32)


In [2]:
# Create a vector
vector = tf.constant([1, 2, 3])
print("Vector:", vector)

Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [4]:
# Create a matrix
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)

Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [5]:
# Create a tensor
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:", tensor)

Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


**2.Find the shape, rank and size of the tensors (which you created for Q1).**