In [1]:
import tensorflow as tf

 **1. Create a vector, scalar, matrix and tensor with values of your choice using tf.constant()**

In [7]:
# Create a scalar
scalar = tf.constant(5)
print("Scalar:", scalar)

Scalar: tf.Tensor(5, shape=(), dtype=int32)


In [8]:
# Create a vector
vector = tf.constant([1, 2, 3])
print("Vector:", vector)

Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [9]:
# Create a matrix
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)

Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [10]:
# Create a tensor
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:", tensor)

Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


**2.Find the shape, rank and size of the tensors (which you created for Q1).**

In [14]:
print("Scalar - Shape:", scalar.shape, "Rank:", tf.rank(scalar).numpy(), "Size:", tf.size(scalar).numpy())
print("Vector - Shape:", vector.shape, "Rank:", tf.rank(vector).numpy(), "Size:", tf.size(vector).numpy())
print("Matrix - Shape:", matrix.shape, "Rank:", tf.rank(matrix).numpy(), "Size:", tf.size(matrix).numpy())
print("Tensor - Shape:", tensor.shape, "Rank:", tf.rank(tensor).numpy(), "Size:", tf.size(tensor).numpy())

Scalar - Shape: () Rank: 0 Size: 1
Vector - Shape: (3,) Rank: 1 Size: 3
Matrix - Shape: (2, 2) Rank: 2 Size: 4
Tensor - Shape: (2, 2, 2) Rank: 3 Size: 8
