In [1]:
import tensorflow as tf

 **1. Create a vector, scalar, matrix and tensor with values of your choice using tf.constant()**

In [7]:
# Create a scalar
scalar = tf.constant(5)
print("Scalar:", scalar)

Scalar: tf.Tensor(5, shape=(), dtype=int32)


In [8]:
# Create a vector
vector = tf.constant([1, 2, 3])
print("Vector:", vector)

Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [9]:
# Create a matrix
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)

Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [10]:
# Create a tensor
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:", tensor)

Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


**2.Find the shape, rank and size of the tensors (which you created for Q1).**

In [14]:
print("Scalar - Shape:", scalar.shape, "Rank:", tf.rank(scalar).numpy(), "Size:", tf.size(scalar).numpy())
print("Vector - Shape:", vector.shape, "Rank:", tf.rank(vector).numpy(), "Size:", tf.size(vector).numpy())
print("Matrix - Shape:", matrix.shape, "Rank:", tf.rank(matrix).numpy(), "Size:", tf.size(matrix).numpy())
print("Tensor - Shape:", tensor.shape, "Rank:", tf.rank(tensor).numpy(), "Size:", tf.size(tensor).numpy())

Scalar - Shape: () Rank: 0 Size: 1
Vector - Shape: (3,) Rank: 1 Size: 3
Matrix - Shape: (2, 2) Rank: 2 Size: 4
Tensor - Shape: (2, 2, 2) Rank: 3 Size: 8


**3.Create two tensors containing random values between 0 and 1 with shape [5,300].**

In [15]:
# Create two tensors with random values between 0 and 1, with shape [5, 300]
tensor1 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)
tensor2 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)

print("Tensor 1:")
print(tensor1)
print("Tensor 2:")
print(tensor2)

Tensor 1:
tf.Tensor(
[[0.50866926 0.34323585 0.06875312 ... 0.70398474 0.28436804 0.954795  ]
 [0.4407617  0.24972486 0.75140464 ... 0.46400607 0.5011853  0.9745331 ]
 [0.41005445 0.5672165  0.4730302  ... 0.39044487 0.3019532  0.5403255 ]
 [0.74893045 0.39412177 0.46800804 ... 0.6631292  0.5188091  0.34921432]
 [0.52533185 0.32006168 0.5434861  ... 0.7179241  0.7723274  0.3415686 ]], shape=(5, 300), dtype=float32)
Tensor 2:
tf.Tensor(
[[0.8037964  0.9401088  0.16081488 ... 0.714708   0.74110925 0.42733443]
 [0.04235852 0.33751655 0.44583797 ... 0.68953884 0.97895205 0.6400398 ]
 [0.4674623  0.31654525 0.43272936 ... 0.9307698  0.43508494 0.6753799 ]
 [0.73404264 0.4311341  0.19812346 ... 0.8996655  0.72960484 0.05689728]
 [0.9880637  0.20429504 0.6000763  ... 0.13621819 0.01385868 0.28384137]], shape=(5, 300), dtype=float32)


**4.Multiply the two tensors (which you created for Question 3) using matrix multiplication. **

In [16]:
# Create two tensors with random values between 0 and 1, with shape [5, 300]
tensor1 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)
tensor2 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)


In [17]:
# Perform matrix multiplication
result = tf.matmul(tensor1, tensor2, transpose_b=True)

In [18]:
# Print the resulting tensor
print("Result of matrix multiplication:")
print(result)

Result of matrix multiplication:
tf.Tensor(
[[69.910835 72.72605  78.3583   72.24144  73.18646 ]
 [69.678955 76.18139  79.70685  73.566666 74.53197 ]
 [71.33916  74.29613  78.62572  72.7796   77.28064 ]
 [67.68257  73.377625 78.45811  70.747765 71.62793 ]
 [68.02311  76.95296  76.86586  75.7589   77.96804 ]], shape=(5, 5), dtype=float32)


**5.Multiply the two tensors (which you created for Question 3) using dot product.**

In [20]:
# Create two tensors with random values between 0 and 1, with shape [5, 300]
tensor1 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)
tensor2 = tf.random.uniform([5, 300], minval=0, maxval=1, dtype=tf.float32)

In [22]:
# Compute the dot product
dot_product = tf.tensordot(tensor1, tensor2, axes=[[1], [1]])


In [23]:
# Print the resulting tensor
print("Result of dot product:")
print(dot_product)

Result of dot product:
tf.Tensor(
[[73.01307  75.611565 73.757515 69.46524  73.84509 ]
 [75.95446  78.40941  75.29412  69.9543   73.48273 ]
 [79.73375  84.68331  79.797615 79.57023  78.26837 ]
 [73.06737  75.45175  71.85271  71.42295  68.94172 ]
 [75.11339  80.94206  75.51499  76.22696  74.56004 ]], shape=(5, 5), dtype=float32)


**6.Create a tensor with random values between 0 and 1 with shape [224, 224,3].**

In [24]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
tensor = tf.random.uniform([224, 224, 3], minval=0, maxval=1, dtype=tf.float32)


In [25]:
# Print the shape and the tensor
print("Shape of the tensor:", tensor.shape)
print("Tensor with random values:")
print(tensor)

Shape of the tensor: (224, 224, 3)
Tensor with random values:
tf.Tensor(
[[[0.8734863  0.6428838  0.3754089 ]
  [0.7495396  0.0965898  0.80765045]
  [0.34526289 0.7162912  0.6851605 ]
  ...
  [0.8755274  0.948923   0.8654144 ]
  [0.21892607 0.24051523 0.26450014]
  [0.15604532 0.99128103 0.74641883]]

 [[0.62833226 0.87507224 0.02012086]
  [0.3337078  0.42475116 0.7861246 ]
  [0.31389642 0.6254504  0.50210154]
  ...
  [0.76508677 0.80990577 0.5802815 ]
  [0.83805525 0.7953849  0.94471514]
  [0.8734821  0.7275212  0.7212305 ]]

 [[0.10087168 0.188115   0.14435816]
  [0.8599702  0.84704053 0.68007517]
  [0.53798234 0.38348687 0.65463567]
  ...
  [0.33029234 0.09139252 0.00389147]
  [0.52879393 0.98597443 0.72800064]
  [0.56564784 0.95855486 0.08341372]]

 ...

 [[0.5277586  0.9802824  0.30676365]
  [0.8238516  0.00850844 0.12333763]
  [0.6661174  0.02303004 0.86215675]
  ...
  [0.7344686  0.6153017  0.76189137]
  [0.8682319  0.75746024 0.99682677]
  [0.8923222  0.939378   0.5729444 ]]

 

**7.Find the min and max values of the tensor (which you created for Question 6)**

In [26]:
# Find the minimum and maximum values of the tensor
min_value = tf.reduce_min(tensor)
max_value = tf.reduce_max(tensor)


In [27]:
# Print the min and max values
print("Min value:", min_value.numpy())
print("Max value:", max_value.numpy())

Min value: 3.2186508e-06
Max value: 0.99999607
